import numpy as np
reps = np.arange(8)
hg1_sim_reps = np.arange(8)
snp_stat_reps = np.arange(10)

gens = [1,10,100,1000]
gens_swordtail = [10,100,200]
swordtail_N = 1000

	
# ===== rules for simulations of human genome  =======

rule make_recmap_slim: # this includes calculation of per locus contribution to rbar whicih takes a while
	input:
		"aau1043_datas3" # sex-averaged recomb map from Halldorsson et al 2019
	output:
		"hg38_wg_slim_recmap.txt",
		"hg38_wg_slim_recmap_verbose.txt",
		"hg38_chr_lengths.txt",
	shell:
		"Rscript --vanilla code/make_hg38_wg_slim_recmap.R"

rule human_wgsims:
	input:
		"hg38_wg_slim_recmap.txt",
		"hg38_chr_lengths.txt"
	output:
		temp("results/human_wgsim_{sim}/replicate{rep}.trees")
	shell:
		"""
		mkdir -p results/human_wgsim_{wildcards.sim}/
		slim -d seed={wildcards.rep} -d N=10000 code/human_wg_{wildcards.sim}.slim
		"""

rule all_human_wgsims:
	input:
		#expand("results/human_wgsim_{sim}/replicate{rep}.trees", sim = ["neutral_equilibrium","neutral_bottleneck","sel1-1000_S0.4","sel1-10_S0.4","sel900-1000_S0.4","neutral_equilibrium_no_interp","neutral_bottleneck_no_interp","sel1-1000_S1","sel1-10_S1", "sel900-1000_S1"], rep = np.arange(10))
		expand("results/human_wgsim_{sim}/replicate{rep}.trees", sim = ["neutral_equilibrium","neutral_bottleneck","sel1-1000_S1","sel1-10_S1","sel900-1000_S1"], rep = np.arange(20))

rule output_human_chrom_ancestry:
	input:
		"results/human_wgsim_{sim}/replicate{rep}.trees"
	output:
		"results/human_wgsim_{sim}/replicate{rep}_frqs.txt"
	shell:
		"python code/ancestry-multigen.py {input} > {output}"

#rule all_human_wgsim_ancestry: # output file will have a row for each rep x generation x snp position.
#	input:
#		expand("results/human_wgsim_{sim}/replicate{rep}_frqs.txt",sim = ["neutral_equilibrium","neutral_bottleneck","neutral_equilibrium_no_interp","sel1-1000"], rep = np.arange(20))

rule human_wgsim_neutral_wavelets:
	input:
		frqs="results/human_wgsim_neutral_{sim}/replicate{rep}_frqs.txt",
		recmap="hg38_wg_slim_recmap_verbose.txt"
	output:
		"results/human_wgsim_neutral_{sim}/replicate{rep}_wavelet_results.RData"
	shell:
		"Rscript --vanilla code/human_wgsim_neutral_wavelets.R {input.frqs} {input.recmap}"

rule human_wgsim_neutral_wavelets_no_interp:
	input:
		frqs="results/human_wgsim_neutral_{sim}_no_interp/replicate{rep}_frqs.txt",
		chrlengths="hg38_chr_lengths.txt"
	output:
		"results/human_wgsim_neutral_{sim}_no_interp/replicate{rep}_wavelet_results.txt"
	shell:
		"Rscript --vanilla code/human_wgsim_neutral_wv_no_interp.R {input.frqs} {input.chrlengths}"
		
rule human_wgsim_sel_wavelets:
	input:
		frqs="results/human_wgsim_sel{sim}/replicate{rep}_frqs.txt",
		recmap="hg38_wg_slim_recmap_verbose.txt"
	output:
		"results/human_wgsim_sel{sim}/replicate{rep}_wavelet_results.RData"
	shell:
		"Rscript --vanilla code/human_wgsim_sel_wavelets.R {input.frqs} {input.recmap}"

rule all_human_wgsim_wavelet_results:
	input:
#		expand("results/human_wgsim_neutral_{sim}_no_interp/replicate{rep}_wavelet_results.txt", rep = np.arange(10), sim = ['equilibrium','bottleneck']),
		expand("results/human_wgsim_{selsim}_S{S}/replicate{rep}_wavelet_results.RData",selsim=['sel1-1000','sel1-10','sel900-1000'],S=['1'], rep=np.arange(20)), 
		expand("results/human_wgsim_sel1-1000_S0.4/replicate{rep}_wavelet_results.RData",rep=np.arange(20)), 

#		expand("results/human_wgsim_{sim}/replicate{rep}_wavelet_results.RData", sim = ["neutral_equilibrium","neutral_bottleneck","sel1-1000","sel1-10","sel900-1000"], rep = np.arange(10))
