import numpy as np
reps = np.arange(20)
gens = ["gen" + num for num in ["0001","0002","0003","0004","0005","0010","0050","0100","0250","0500","0750","1000"]]
sims = ["neutral-const-recomb","sel-const-recomb","neutral-periodic-recomb","sel-periodic-recomb"]

rule all:
	input:
		expand("results/{sim}/ancestry_master.txt", sim=sims)

rule simulation:
	input:
	output:
		expand("results/{{sim}}/replicate{{rep}}_{gen}.trees", gen=gens)
	shell:
		"slim -d seed={wildcards.rep} code/{wildcards.sim}.slim"

rule ancestry_calc:
	input:
		"results/{sim}/{rep_gen}.trees"
	output:
		"results/{sim}/{rep_gen}_ancestry.txt"
	shell:
		"python code/derived-allele-freq.py {input} > {output}"

rule aggregate:
	input:
		expand("results/{{sim}}/replicate{rep}_{gen}_ancestry.txt", rep=reps, gen=gens)
	output:
		"results/{sim}/ancestry_master.txt"
	shell:
		"cat {input} > results/{wildcards.sim}/ancestry_master.txt"

