import numpy as np
reps = [0]#np.arange(20)
gens = ["gen0002","gen0005", "gen0010"]#, "gen0050", "gen0100", "gen0500", "gen0750", "gen1000"]
sims = ["neutral-const-recomb","sel-const-recomb","neutral-periodic-recomb","sel-periodic-recomb"]

rule all:
	input:
		expand("results/{sim}/ancestry_master.txt", sim=sims)

rule simulation:
	input:
	output:
		expand("results/{{sim}}/replicate{{rep}}_{gen}.trees", gen=gens)
	shell:
		"slim -d seed={wildcards.rep} code/{wildcards.sim}.slim"

rule ancestry_calc:
	input:
		"results/{sim}/{rep_gen}.trees"
	output:
		"results/{sim}/{rep_gen}_ancestry.txt"
	shell:
		"python code/ancestry.py {input} > {output}"

rule aggregate:
	input:
		expand("results/{{sim}}/replicate{rep}_{gen}_ancestry.txt", rep=reps, gen=gens)
	output:
		"results/{sim}/ancestry_master.txt"
	shell:
		"cat {input} > results/{wildcards.sim}/ancestry_master.txt"
